In [1]:
#import dependencies 
from numpy.random import seed
from numpy.random import randn
from scipy import stats
import numpy as np

import math  

import seaborn as sns
sns.set(style="darkgrid")
from matplotlib import pyplot as plt

import pandas as pd
import os

In [2]:
#check list of files in data directory 
print(os.listdir("./data"))

['newdata_iperf_m5d_48 - newdata_iperf_m5d_48.csv', 'ycruncher_m5d_aug13_48-instances - ycruncher_m5d_aug13.csv', 'm5d_48vms_pgbench_2ndtry - m5d_48vms_pgbench_2ndtry.csv', 'm5d-sysbench-dedicated-host-10-24-2019 - m5d-sysbench-dedicated-host-10-24-2019.csv', 'y_cruncher_08_22_2019 - y_cruncher_08_22_2019.csv', 'm5d-y-cruncher-idle-mode-10-27-2019 - m5d-ycruncher-p-10-27-2019.csv']

In [3]:
data_y_cruncher_idle_shutdown = 'm5d-y-cruncher-idle-mode-10-27-2019 - m5d-ycruncher-p-10-27-2019.csv'

In [11]:
df_y_cruncher_shutdown = pd.read_csv("./data/" + data_y_cruncher_idle_shutdown, header = 0)

In [12]:
#remove idle vm rows
df_y_cruncher_shutdown.dropna(subset=['processorInfo'], inplace= True)

In [17]:
df_y_cruncher_shutdown

               instanceID  setId  wallTime
0     i-0576c464a37051792    0.0  6.408017
1     i-0576c464a37051792    0.0  5.812473
2     i-0576c464a37051792    0.0  5.782898
145   i-0576c464a37051792    1.0  5.798171
146   i-0576c464a37051792    1.0  5.766209
147   i-0576c464a37051792    1.0  5.721492
287   i-0576c464a37051792    2.0  5.930911
288   i-0576c464a37051792    2.0  5.874934
289   i-0576c464a37051792    2.0  5.713738
426   i-0576c464a37051792    3.0  5.798898
427   i-0576c464a37051792    3.0  5.758433
428   i-0576c464a37051792    3.0  5.816252
562   i-0576c464a37051792    4.0  5.888732
563   i-0576c464a37051792    4.0  5.748517
564   i-0576c464a37051792    4.0  5.687981
695   i-0576c464a37051792    5.0  5.788118
696   i-0576c464a37051792    5.0  5.735853
697   i-0576c464a37051792    5.0  5.710460
825   i-0576c464a37051792    6.0  5.906888
826   i-0576c464a37051792    6.0  6.030623
827   i-0576c464a37051792    6.0  5.845923
952   i-0576c464a37051792    7.0  5.788566
953   i-0576c464a37051792    7.0  5.906671
954   i-0576c464a37051792    7.0  5.816617
1076  i-0576c464a37051792    8.0  5.778954
1077  i-0576c464a37051792    8.0  5.857117
1078  i-0576c464a37051792    8.0  5.970866
1197  i-0576c464a37051792    9.0  5.774925
1198  i-0576c464a37051792    9.0  5.883913
1199  i-0576c464a37051792    9.0  5.977598
...                   ...    ...       ...
3401  i-0576c464a37051792   38.0  4.839004
3402  i-0576c464a37051792   38.0  4.803826
3403  i-0576c464a37051792   38.0  4.842818
3432  i-0576c464a37051792   39.0  5.036340
3433  i-0576c464a37051792   39.0  4.810576
3434  i-0576c464a37051792   39.0  4.789473
3460  i-0576c464a37051792   40.0  4.909524
3461  i-0576c464a37051792   40.0  4.713288
3462  i-0576c464a37051792   40.0  4.961626
3485  i-0576c464a37051792   41.0  5.055857
3486  i-0576c464a37051792   41.0  4.847195
3487  i-0576c464a37051792   41.0  4.727100
3507  i-0576c464a37051792   42.0  4.903094
3508  i-0576c464a37051792   42.0  4.714858
3509  i-0576c464a37051792   42.0  4.845802
3526  i-0576c464a37051792   43.0  4.868011
3527  i-0576c464a37051792   43.0  4.715051
3528  i-0576c464a37051792   43.0  4.702464
3542  i-0576c464a37051792   44.0  4.802926
3543  i-0576c464a37051792   44.0  4.993961
3544  i-0576c464a37051792   44.0  4.989726
3555  i-0576c464a37051792   45.0  4.793360
3556  i-0576c464a37051792   45.0  4.625178
3557  i-0576c464a37051792   45.0  4.884169
3565  i-0576c464a37051792   46.0  4.595461
3566  i-0576c464a37051792   46.0  4.451220
3567  i-0576c464a37051792   46.0  4.699745
3572  i-0576c464a37051792   47.0  5.805563
3573  i-0576c464a37051792   47.0  5.898833
3574  i-0576c464a37051792   47.0  6.047128

[144 rows x 3 columns]

In [14]:
df_y_cruncher_shutdown.drop(df_y_cruncher_shutdown.columns[[1,3,4,5,6,7,8,9,10,11,12,13,14,16,17]], axis = 1, inplace=True)
#df_y_cruncher_shutdown.dropna()

In [15]:
df_y_cruncher_shutdown.head()

              instanceID  setId  wallTime
0    i-0576c464a37051792    0.0  6.408017
1    i-0576c464a37051792    0.0  5.812473
2    i-0576c464a37051792    0.0  5.782898
145  i-0576c464a37051792    1.0  5.798171
146  i-0576c464a37051792    1.0  5.766209

In [16]:
df_y_cruncher_shutdown.describe()

            setId    wallTime
count  144.000000  144.000000
mean    23.500000    5.335917
std     13.901753    0.469157
min      0.000000    4.451220
25%     11.750000    4.846847
50%     23.500000    5.258299
75%     35.250000    5.777563
max     47.000000    6.408017

In [ ]:
#remove idle vm rows

In [20]:
#group by tenants / setId 
mean = df_y_cruncher_shutdown.groupby('setId').mean()
mean.head()

       wallTime
setId
0.0    6.001129
1.0    5.761957
2.0    5.839861
3.0    5.791194
4.0    5.775077

In [21]:
#create std, normalized data
std = df_y_cruncher_shutdown.groupby('setId').std()
std.head()

       wallTime
setId
0.0    0.352685
1.0    0.038516
2.0    0.112755
3.0    0.029669
4.0    0.102977

In [27]:
#add normalized column
test['normalized'] = test.loc[:,'wallTime':].div(test.iloc[-1]['wallTime':])

In [29]:
test['std'] = std

In [32]:
#reverse table
test=test.iloc[::-1]

       wallTime  normalized       std
setId
47.0   5.917175    1.291356  0.121823
46.0   4.582142    1.000000  0.124797
45.0   4.767569    1.040467  0.131408
44.0   4.928871    1.075670  0.109092
43.0   4.761842    1.039217  0.092160
42.0   4.821252    1.052183  0.096490
41.0   4.876717    1.064288  0.166355
40.0   4.861479    1.060962  0.130955
39.0   4.878796    1.064741  0.136844
38.0   4.828549    1.053776  0.021496
37.0   4.832912    1.054728  0.011085
36.0   4.941408    1.078406  0.228125
35.0   4.824981    1.052997  0.040099
34.0   4.825440    1.053097  0.028121
33.0   4.838194    1.055880  0.023884
32.0   4.850455    1.058556  0.064189
31.0   4.824833    1.052965  0.019794
30.0   4.860526    1.060754  0.070526
29.0   5.145900    1.123034  0.368729
28.0   5.008924    1.093140  0.155564
27.0   4.890060    1.067200  0.081934
26.0   5.334640    1.164224  0.202560
25.0   5.397287    1.177896  0.240927
24.0   5.180473    1.130579  0.054001
23.0   5.182360    1.130991  0.041220
22.0   5.351280    1.167855  0.111759
21.0   5.199519    1.134736  0.083889
20.0   5.163815    1.126944  0.028434
19.0   5.665151    1.236354  0.114639
18.0   5.747930    1.254420  0.169883
17.0   5.631662    1.229046  0.074603
16.0   5.686082    1.240922  0.037878
15.0   5.978174    1.304668  0.104030
14.0   5.772804    1.259848  0.090289
13.0   5.748892    1.254630  0.028160
12.0   5.911665    1.290153  0.147649
11.0   5.860722    1.279035  0.147273
10.0   5.816597    1.269406  0.065933
9.0    5.878812    1.282983  0.101433
8.0    5.868979    1.280837  0.096504
7.0    5.837285    1.273921  0.061706
6.0    5.927811    1.293677  0.094111
5.0    5.744810    1.253739  0.039596
4.0    5.775077    1.260344  0.102977
3.0    5.791194    1.263862  0.029669
2.0    5.839861    1.274483  0.112755
1.0    5.761957    1.257481  0.038516
0.0    6.001129    1.309678  0.352685

In [36]:
#add tenants
test['tenants'] = np.arange(len(test))+1

/Users/dell/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [42]:
#print csv
cols = ['tenants', 'wallTime', 'std']

In [43]:
test = test[cols]